# Docker Composeのバージョン
version: "3"

# サービスの定義
services:
  # "frontend"というサービスの設定
  frontend:
    # イメージのビルド情報
    container_name: frontend-app
    build:
      # Dockerイメージをビルドするためのコンテキスト
      context: .
      # Dockerfileの場所
      dockerfile: ./docker/frontend/Dockerfile

    # ユーザをnodeに変更
    user: "node"

    # 作業ディレクトリの設定
    working_dir: /home/node/frontend

    # システム環境最適化
    environment:
      - NODE_ENV=production
      
    # ボリュームのマウント設定
    volumes:
      - ./frontend:/home/node/frontend 

    # コンテナ内で実行されるコマンド
    command: node

    # 公開用のポート指定。ホスト側:コンテナ側
    ports:
      - '5173:5173'

    # ttyを有効にする（コンテナと対話的なセッションを可能にする）
    tty: true